<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>foo</string>
	</array>
	<key>name</key>
	<string>Unibasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#numericLiterals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#basicStatements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>basicStatements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(ABORT|ACTIVATEKEY|AUTHORIZATION|AUXMAP)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(BEGIN|BREAK|BSCAN)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(CALL|CALLING|CAPTURING|CASE|CHAIN|CLEAR|CLEARDATA|CLEARFILE|CLEARPROMPTS|CLEARSELECT|CLOSE)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(CLOSESEQ|COMMIT|COMMON|CONTINUE|CREATE|CRT)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(DATA|DEACTIVATEKEY|DEBUG|DEFFUN|DELETE|DELETELIST|DELETEU|DIMENSION|DISABLEDEC|DISPLAY)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ECHO|ELSE|ENABLEDEC|END|ENTER|EOF|EQUATE|ERRMSG|ERROR|EXECUTE|EXIT)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(FILELOCK|FILEUNLOCK|FIND|FINDSTR|FLUSH|FOOTING|FOR|FROM|FUNCTION)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(GET|GETLIST|GETX|GOSUB|GOTO|GROUPSTORE)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(HEADING|HUSH)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(IF|INCLUDE|INPUT|INPUTCLEAR|INPUTDISP|INPUTDP|INPUTERR|INPUTNULL|INPUTTRAP|INS|ISOLATION)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(LOCATE|LOCK|LOOP)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(MAT|MATBUILD|MATPARSE|MATREAD|MATREADL|MATREADU|MATWRITE|MATWRITEU)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(NEXT)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(OFF|ON|OPEN|OPENDEV|OPENPATH|OPENSEQ)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(PAGE|PERFORM|PRECISION|PRINT|PRINTER|PRINTERR|PROCREAD|PROCWRITE|PROGRAM|PROMPT)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(RANDOMIZE|READ|READBLK|READL|READLIST|READNEXT|READSEQ|READT|READU|READV|READVL|READVU|RELEASE)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(REPEAT|RESET|RETURN|RETURNING|REVREMOVE|REWIND|ROLLBACK)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(SELECT|SELECTE|SELECTINDEX|SELECTINFO|SEND|SET|SETREM|SLEEP|SSELECT|START|STOP|SUBROUTINE)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TABSTOP|THEN|TIMEOUT|TO|TPRINT|TRANSACTION|TTYCTL|TTYGET|TTYSET)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(UNLOCK|UNTIL)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(WEOF|WEOFSEQ|WHILE|WRITE|WRITEBLK|WRITELIST|WRITESEQ|WRITESEQF|WRITET|WRITEU|WRITEV|WRITEVU)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\$)%(CHAIN|COPYRIGHT|DEFINE|EJECT|IFDEF|IFNDEF|INCLUDE|INSERT|MAP|OPTIONS|PAGE|UNDEFINE)\b</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:and|or|not)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.unibasic</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s(\*|REM|!).*$
?</string>
					<key>name</key>
					<string>comment.line.unibasic</string>
				</dict>
			</array>
		</dict>
		<key>numericLiterals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.unibasic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>keyword.unibasic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.unibasic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.unibasic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\d+(\.)(?:\d+)?</string>
					<key>name</key>
					<string>keyword.unibasic</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.unibasic</string>
	<key>uuid</key>
	<string>181b5684-d089-4311-9ce5-aebdcd5648bd</string>
</dict>
</plist>
