<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>foo</string>
	</array>
	<key>name</key>
	<string>Unibasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#numericLiterals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#basicStatements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>basicStatements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w(ABORT|ACTIVATEKEY|AUTHORIZATION|AUXMAP)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(BEGIN|BREAK|BSCAN)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(CALL|CALLING|CAPTURING|CASE|CLEAR|CLEARDATA|CLEARFILE|CLEARPROMPTS|CLEARSELECT|CLOSE)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(CLOSESEQ|COMMIT|COMMON|CONTINUE|CREATE|CRT)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(DATA|DEACTIVATEKEY|DEBUG|DEFFUN|DELETE|DELETELIST|DELETEU|DIMENSION|DISABLEDEC|DISPLAY|DO)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(ECHO|ELSE|ENABLEDEC|END|ENTER|EOF|EQUATE|ERRMSG|ERROR|EXECUTE|EXIT)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(FILELOCK|FILEUNLOCK|FIND|FINDSTR|FLUSH|FOOTING|FOR|FROM|FUNCTION)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(GET|GETLIST|GETX|GOSUB|GOTO|GROUPSTORE)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(HEADING|HUSH)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(IF|INPUT|INPUTCLEAR|INPUTDISP|INPUTDP|INPUTERR|INPUTNULL|INPUTTRAP|INS|ISOLATION)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(LOCATE|LOCK|LOOP)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(MAT|MATBUILD|MATPARSE|MATREAD|MATREADL|MATREADU|MATWRITE|MATWRITEU)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(NEXT)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(OFF|ON|OPEN|OPENDEV|OPENPATH|OPENSEQ)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(PERFORM|PRECISION|PRINT|PRINTER|PRINTERR|PROCREAD|PROCWRITE|PROGRAM|PROMPT)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(RANDOMIZE|READ|READBLK|READL|READLIST|READNEXT|READSEQ|READT|READU|READV|READVL|READVU|RELEASE)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(REPEAT|RESET|RETURN|RETURNING|REVREMOVE|REWIND|ROLLBACK)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(SELECT|SELECTE|SELECTINDEX|SELECTINFO|SEND|SET|SETREM|SLEEP|SSELECT|START|STOP|SUBROUTINE)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(TABSTOP|THEN|TIMEOUT|TO|TPRINT|TRANSACTION|TTYCTL|TTYGET|TTYSET)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(UNLOCK|UNTIL)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(WEOF|WEOFSEQ|WHILE|WRITE|WRITEBLK|WRITELIST|WRITESEQ|WRITESEQF|WRITET|WRITEU|WRITEV|WRITEVU)\w</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(CHAIN|COPYRIGHT|DEFINE|EJECT|IFDEF|IFNDEF|INCLUDE|INSERT|MAP|OPTIONS|PAGE|UNDEFINE)</string>
					<key>name</key>
					<string>keyword.other.unibasic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w(?i:and|or|not)\w</string>
					<key>name</key>
					<string>keyword.operator.logical.unibasic</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*(REM|[!*])[^;]*$</string>
					<key>name</key>
					<string>comment.line.unibasic</string>
				</dict>
			</array>
		</dict>
		<key>numericLiterals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.unibasic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>keyword.unibasic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.unibasic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.unibasic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\d+(\.)(?:\d+)?</string>
					<key>name</key>
					<string>keyword.unibasic</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.unibasic</string>
	<key>uuid</key>
	<string>181b5684-d089-4311-9ce5-aebdcd5648bd</string>
</dict>
</plist>
